#!/bin/sh
set -eu

cat > /usr/share/nginx/html/runtime-config.js <<EOF
window.__APP_CONFIG__ = {
  "REACT_APP_KEYCLOAK_BASE_URL": "${REACT_APP_KEYCLOAK_BASE_URL:-}",
  "REACT_APP_KEYCLOAK_TOKEN_URL": "${REACT_APP_KEYCLOAK_TOKEN_URL:-}",
  "REACT_APP_USER_SERVICE_BASE_URL": "${REACT_APP_USER_SERVICE_BASE_URL:-}",
  "REACT_APP_LOGIN_URL": "${REACT_APP_LOGIN_URL:-}",
  "REACT_APP_USER_INFO_URL": "${REACT_APP_USER_INFO_URL:-}",
  "REACT_APP_USER_UPDATE_URL": "${REACT_APP_USER_UPDATE_URL:-}",
  "REACT_APP_REGISTER_URL": "${REACT_APP_REGISTER_URL:-}",
  "REACT_APP_REGISTER_CONFIRM_URL": "${REACT_APP_REGISTER_CONFIRM_URL:-}",
  "REACT_APP_REGISTER_CREATE_CONFIRM_URL": "${REACT_APP_REGISTER_CREATE_CONFIRM_URL:-}",
  "REACT_APP_LOGOUT_URL": "${REACT_APP_LOGOUT_URL:-}",
  "REACT_APP_KEYCLOAK_CLIENT_ID": "${REACT_APP_KEYCLOAK_CLIENT_ID:-}",
  "REACT_APP_KEYCLOAK_GRANT_TYPE": "${REACT_APP_KEYCLOAK_GRANT_TYPE:-}",
  "REACT_APP_MY_USER_INFO_URL": "${REACT_APP_MY_USER_INFO_URL:-}",
  "REACT_APP_MY_ORDER_URL": "${REACT_APP_MY_ORDER_URL:-}",
  "REACT_APP_MY_ADDRESS_URL": "${REACT_APP_MY_ADDRESS_URL:-}",
  "REACT_APP_USE_DEMO_LOCAL_AUTH": "${REACT_APP_USE_DEMO_LOCAL_AUTH:-false}",
  "REACT_APP_PROMO_IMAGES_URL": "${REACT_APP_PROMO_IMAGES_URL:-}",
  "REACT_APP_USE_STATIC_PROMO_IMAGES": "${REACT_APP_USE_STATIC_PROMO_IMAGES:-true}",
  "REACT_APP_CAMPAIGN_ITEMS_URL": "${REACT_APP_CAMPAIGN_ITEMS_URL:-}",
  "REACT_APP_USE_STATIC_CAMPAIGN_ITEMS": "${REACT_APP_USE_STATIC_CAMPAIGN_ITEMS:-true}",
  "REACT_APP_PRODUCT_LIST_URL": "${REACT_APP_PRODUCT_LIST_URL:-}",
  "REACT_APP_PRODUCT_DETAIL_URL": "${REACT_APP_PRODUCT_DETAIL_URL:-}",
  "REACT_APP_PRODUCT_FACETS_URL": "${REACT_APP_PRODUCT_FACETS_URL:-}",
  "REACT_APP_USE_STATIC_PRODUCT_DATA": "${REACT_APP_USE_STATIC_PRODUCT_DATA:-true}",
  "REACT_APP_SEARCH_URL": "${REACT_APP_SEARCH_URL:-}",
  "REACT_APP_USE_STATIC_SEARCH_DATA": "${REACT_APP_USE_STATIC_SEARCH_DATA:-true}",
  "REACT_APP_FAVORITE_LIST_URL": "${REACT_APP_FAVORITE_LIST_URL:-}",
  "REACT_APP_FAVORITE_TOGGLE_URL": "${REACT_APP_FAVORITE_TOGGLE_URL:-}",
  "REACT_APP_USE_STATIC_FAVORITE_DATA": "${REACT_APP_USE_STATIC_FAVORITE_DATA:-true}"
};
EOF

exec nginx -g 'daemon off;'
